name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS
        uses: actions/upload-artifact@v2.2.3
        with:
          name: DOWNLOADS-Ubuntu
          path: DOWNLOADS

  build_macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS
        uses: actions/upload-artifact@v2.2.3
        with:
          name: DOWNLOADS-MacOS
          path: DOWNLOADS
