name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - uses: actions/checkout@v4.2.2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload package
        uses: actions/upload-artifact@v4.5.0
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS.txt
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-info-Ubuntu
          path: DOWNLOADS.txt

      - name: Upload downloads
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-Ubuntu
          path: downloads

      - name: Generate artifact hashes
        shell: bash
        id: hash
        run: |
          cd upload && echo "artifact_hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"

    outputs:
      artifact_hashes: ${{ steps.hash.outputs.artifact_hashes }}

  # Sign in a separate job to limit ID token exposure
  sign_ubuntu:
    needs: [build_ubuntu]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Install cosign
        #if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign artifact hashes
        #if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ${{ needs.build_ubuntu.outputs.artifact_hashes }} | base64 -d > ARTIFACT_SHA256SUMS
          cosign sign-blob -y ARTIFACT_SHA256SUMS

  build_macos:
    runs-on: macos-13

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - uses: actions/checkout@v4.2.2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v4.5.0
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS.txt
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-info-MacOS
          path: DOWNLOADS.txt

      - name: Upload downloads
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-MacOS
          path: downloads
        
      - name: Generate artifact hashes
        shell: bash
        id: hash
        run: |
          cd upload && echo "artifact_hashes=$(shasum -a 256 * | base64)" >> "$GITHUB_OUTPUT"

    outputs:
      artifact_hashes: ${{ steps.hash.outputs.artifact_hashes }}

  # Sign in a separate job to limit ID token exposure
  sign_macos:
    needs: [build_macos]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Install cosign
        #if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign artifact hashes
        #if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ${{ needs.build_macos.outputs.artifact_hashes }} | base64 -d > ARTIFACT_SHA256SUMS
          cosign sign-blob -y ARTIFACT_SHA256SUMS

  build_macos_aarch64:
    runs-on: macos-14

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - uses: actions/checkout@v4.2.2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v4.5.0
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS.txt
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-info-MacOS
          path: DOWNLOADS.txt

      - name: Upload downloads
        uses: actions/upload-artifact@v4.5.0
        with:
          name: downloads-MacOS
          path: downloads
        
      - name: Generate artifact hashes
        shell: bash
        id: hash
        run: |
          cd upload && echo "artifact_hashes=$(shasum -a 256 * | base64)" >> "$GITHUB_OUTPUT"

    outputs:
      artifact_hashes: ${{ steps.hash.outputs.artifact_hashes }}

  # Sign in a separate job to limit ID token exposure
  sign_macos_aarch64:
    needs: [build_macos_aarch64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Install cosign
        #if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign artifact hashes
        #if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ${{ needs.build_macos_aarch64.outputs.artifact_hashes }} | base64 -d > ARTIFACT_SHA256SUMS
          cosign sign-blob -y ARTIFACT_SHA256SUMS
