name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS.txt
        uses: actions/upload-artifact@v2.2.3
        with:
          name: downloads-info-Ubuntu
          path: DOWNLOADS.txt

      - name: Upload downloads
        uses: actions/upload-artifact@v2.2.3
        with:
          name: downloads-Ubuntu
          path: downloads

  build_macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

      - name: Upload DOWNLOADS.txt
        uses: actions/upload-artifact@v2.2.3
        with:
          name: downloads-info-MacOS
          path: DOWNLOADS.txt

      - name: Upload downloads
        uses: actions/upload-artifact@v2.2.3
        with:
          name: downloads-MacOS
          path: downloads
