name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*

      - name: Generate hashes
        shell: bash
        id: hash
        run: |
          cd upload && echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"

    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

  provenance_ubuntu:
    needs: [build_ubuntu]
    permissions:
      actions: read
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.5.0
    with:
      base64-subjects: "${{ needs.build_ubuntu.outputs.hashes }}"

  build_macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*
